name: release

on:
  push:
    branches: [dev]
    # tags:
    #   - 'v*'

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        include:
          - os: macos-10.15
            kind: build
          - os: windows-2019
            kind: build
          - os: ubuntu-latest
            kind: build
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install Deno
        if: |
          !startsWith(matrix.os, 'windows')
        run: |-
          curl -fsSL https://deno.land/x/install/install.sh | sh
          echo "$HOME/.deno/bin" >> $GITHUB_PATH
      - name: Install Node
        uses: actions/setup-node@v2
      - name: Install Deno (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |-
          curl -fsSL https://deno.land/x/install/install.sh | sh
          echo "$HOME/.deno/bin" >> $env:GITHUB_PATH
      - name: Install esbuild
        run: npm install -g esbuild
      - name: Log versions
        run: |
          deno --version
          node --version
          esbuild --version
      - name: bundle
        run: ./scripts/bundle.sh
        shell: bash
      - if: startsWith(matrix.os, 'windows')
        run: |
          ls
          ./moviematch.exe --version
      - if: |
          !startsWith(matrix.os, 'windows')
        run: |
          ls
          ./moviematch --version