name: Release

on:
  push:
    tags:
      - 'v2*'

jobs:
  build:
    name: compile
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install Deno
        run: |-
          curl -fsSL https://deno.land/x/install/install.sh | sh
          echo "$HOME/.deno/bin" >> $GITHUB_PATH
          export PATH="$DENO_INSTALL/bin:$PATH"
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
      - name: Upgrade Deno to Canary
        run: deno upgrade --canary
      - name: Install esbuild
        run: npm install -g esbuild
      - name: bundle
        run: ./scripts/bundle.sh
        shell: bash
      - name: Print MovieMatch version
        if: startsWith(matrix.os, 'windows')
        run: .\moviematch.exe --version
      - name: Print MovieMatch version
        if: |
          !startsWith(matrix.os, 'windows')
        run: ./moviematch --version
      - name: Upload binary
        uses: actions/upload-artifact@v2
        if: startsWith(matrix.os, 'windows')
        with:
          name: moviematch-windows
          path: moviematch.exe
      - name: Upload binary
        uses: actions/upload-artifact@v2
        if: |
          !startsWith(matrix.os, 'windows')
        with:
          name: moviematch-${{ runner.os }}
          path: moviematch