name: Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    - uses: denolib/setup-deno@v2
      with:
        deno-version: v1.7.4
    - run: |
        chmod +x ./scripts/test.sh
        ./scripts/test.sh
